import Navbar from '@/components/Navbar';
import Link from 'next/link';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Impressum – Website Analyser',
  description: 'Legal notice for Website Analyser by Lweb.',
};

export default function ImpressumPage() {
  return (
    <>
      <Navbar />
      <main className="legal-page">
        <div className="legal-container">
          <Link href="/" className="legal-back">← Back</Link>

          <h1>Impressum</h1>
          <p className="legal-date">Legal notice pursuant to § 5 TMG / Art. 3 UWG</p>

          <h2>Provider</h2>
          <p>
            <strong>Lweb</strong><br />
            Switzerland<br />
            <a href="https://lweb.ch" target="_blank" rel="noopener noreferrer">lweb.ch</a>
          </p>

          <h2>Contact</h2>
          <p>
            For any enquiries, please use the contact form available at{' '}
            <a href="https://lweb.ch" target="_blank" rel="noopener noreferrer">lweb.ch</a>.
          </p>

          <h2>Responsible for content</h2>
          <p>Lweb — address as above.</p>

          <h2>Disclaimer</h2>
          <p>
            The analysis results generated by this tool are produced by an AI model and are provided for informational purposes only.
            They do not constitute professional advice. We accept no liability for decisions made on the basis of these results.
          </p>
          <p>
            All external links were checked at the time of publication. We have no influence over the content of linked external sites
            and accept no responsibility for them.
          </p>

          <h2>Copyright</h2>
          <p>
            The content and works on this website are subject to Swiss and German copyright law.
            Reproduction, adaptation, distribution or any form of commercialisation of such material beyond the scope of the copyright law
            requires the prior written consent of Lweb.
          </p>
        </div>
      </main>
    </>
  );
}
